"""os_log annotation value→name decoder tables (AUTO-GENERATED).

DO NOT EDIT BY HAND. Regenerate with `python scripts/gen_decoders.py`.

Ported from the Mandiant *macos-unifiedlogs* Rust library
(version 0.5.1, Apache-2.0): https://github.com/mandiant/macos-unifiedlogs
Only pure value→name lookup tables are ported here; byte-parsing decoders
(sockaddr, IPv4/6, DNS headers, timestamps) remain hand-written in message.py.
See THIRD_PARTY_NOTICES.md for the full attribution and licence.
"""

from __future__ import annotations

# annotation type (lowercased) → {raw value: decoded name}
DECODER_TABLES: dict[str, dict[str, str]] = {
    'darwin.errno': {
        '0': 'Success',
        '1': 'Operation not permitted',
        '2': 'No such file or directory',
        '3': 'No such process',
        '4': 'Interrupted system call',
        '5': 'Input/Output error',
        '6': 'Device not configured',
        '7': 'Argument list too long',
        '8': 'Exec format error',
        '9': 'Bad file descriptor',
        '10': 'No child processes',
        '11': 'Resource deadlock avoided',
        '12': 'Cannot allocate memory',
        '13': 'Permission denied',
        '14': 'Bad address',
        '15': 'Block device required',
        '16': 'Device / Resource busy',
        '17': 'File exists',
        '18': 'Cross-device link',
        '19': 'Operation not supported by device',
        '20': 'Not a directory',
        '21': 'Is a directory',
        '22': 'Invalid arguement',
        '23': 'Too many open files in system',
        '24': 'Too many open files',
        '25': 'Inappropriate ioctl for devices',
        '26': 'Text file busy',
        '27': 'File too large',
        '28': 'No space left on device',
        '29': 'Illegal seek',
        '30': 'Read-only filesystem',
        '31': 'Too many link',
        '32': 'Broken pipe',
        '33': 'Numerical argument out of domain',
        '34': 'Result too large',
        '35': 'Resource temporarily unavailable, operation would block',
        '36': 'Operation now in progress',
        '37': 'Operation already in progress',
        '38': 'Socket operation on non-socket',
        '39': 'Destination address required',
        '40': 'Message too long',
        '41': 'Protocol wrong type for socket',
        '42': 'Protocol not available',
        '43': 'Protocol not supported',
        '44': 'Socket type not supported',
        '45': 'Operation not supported, Operation not supported on socket',
        '46': 'Protocol family not supported',
        '47': 'Address family not supported by protocol family',
        '48': 'Address already in use',
        '49': "Can't assign requested address",
        '50': 'Network is down',
        '51': 'Network is unreachable',
        '52': 'Network dropped connection on reset',
        '53': 'Software caused connection abort',
        '54': 'Connection reset by peer',
        '55': 'No buffer space available',
        '56': 'Socket is already connected',
        '57': 'Socket is not connected',
        '58': "Can't send after socket shutdown",
        '59': "Too many references: can't splice",
        '60': 'Operation timed out',
        '61': 'Connection refused',
        '62': 'Too many levels of symbolic links',
        '63': 'File name too long',
        '64': 'Host is down',
        '65': 'No route to host',
        '66': 'Directory not empty',
        '67': 'Too many processes',
        '68': 'Too many users',
        '69': 'Disc quota exceeded',
        '70': 'Stale NFS file handle',
        '71': 'Too many levels of remote in path',
        '72': 'RPC struct is bad',
        '73': 'RPC version wrong',
        '74': 'RPC prog. not avail',
        '75': 'Program version wrong',
        '76': 'Bad procedure for program',
        '77': 'No locks available',
        '78': 'Function not implemented',
        '79': 'Inappropriate file type or format',
        '80': 'Authentication error',
        '81': 'Need authenticator',
        '82': 'Device power is off',
        '83': 'Device error, e.g. paper out',
        '84': 'Value too large to be stored in data type',
        '85': 'Bad executable',
        '86': 'Bad CPU type in executable',
        '87': 'Shared library version mismatch',
        '88': 'Malformed Macho file',
        '89': 'Operation canceled',
        '90': 'Identifier removed',
        '91': 'No message of desired type',
        '92': 'Illegal byte sequence',
        '93': 'Attribute not found',
        '94': 'Bad message',
        '95': 'Reserved',
        '96': 'No message available on STREAM',
        '97': 'Reserved',
        '98': 'No STREAM resources',
        '99': 'Not a STREAM',
        '100': 'Protocol error',
        '101': 'STREAM ioctl timeout',
        '102': 'Operation not supported on socket',
        '103': 'No such policy registered',
        '104': 'State not recoverable',
        '105': 'Previous owner died',
        '106': 'Interface output queue is full, Must be equal largest errno',
        '-1': 'Restart syscall',
        '-2': "Don't modify regs, just return",
        '-5': 'Restart lookup under heavy vnode pressure/recycling',
        '-6': 'Red drive open',
        '-7': 'Keep looking',
        '-8': 'Data less',
    },
    'location:clclientauthorizationstatus': {
        '0': 'Not Determined',
        '1': 'Restricted',
        '2': 'Denied',
        '3': 'Authorized Always',
        '4': 'Authorized When In Use',
    },
    'location:cldaemonstatus_type::reachability': {
        '0': 'Reachability Unavailable',
        '1': 'Reachability Small',
        '2': 'Reachability Large',
        '56': 'Reachability Unachievable',
    },
    'location:clsubharvesteridentifier': {
        '0': 'CellLegacy',
        '1': 'Cell',
        '2': 'Wifi',
        '3': 'Tracks',
        '4': 'Realtime',
        '5': 'App',
        '6': 'Pass',
        '7': 'Indoor',
        '8': 'Pressure',
        '9': 'Poi',
        '10': 'Trace',
        '11': 'Avenger',
        '12': 'Altimeter',
        '13': 'Ionosphere',
        '14': 'Unknown',
    },
    'location:iomessage': {
        '3758097008': 'CanSystemSleep',
        '3758097024': 'SystemWillSleep',
        '3758097040': 'SystemWillNotSleep',
        '3758097184': 'SystemWillPowerOn',
        '3758097168': 'SystemWillRestart',
        '3758097152': 'SystemHasPoweredOn',
        '3758097200': 'CopyClientID',
        '3758097216': 'SystemCapabilityChange',
        '3758097232': 'DeviceSignaledWakeup',
        '3758096400': 'ServiceIsTerminated',
        '3758096416': 'ServiceIsSuspended',
        '3758096432': 'ServiceIsResumed',
        '3758096640': 'ServiceIsRequestingClose',
        '3758096641': 'ServiceIsAttemptingOpen',
        '3758096656': 'ServiceWasClosed',
        '3758096672': 'ServiceBusyStateChange',
        '3758096680': 'ConsoleSecurityChange',
        '3758096688': 'ServicePropertyChange',
        '3758096896': 'CanDevicePowerOff',
        '3758096912': 'DeviceWillPowerOff',
        '3758096928': 'DeviceWillNotPowerOff',
        '3758096944': 'DeviceHasPoweredOn',
        '3758096976': 'SystemWillPowerOff',
        '3758096981': 'SystemPagingOff',
    },
    'mdns:gaiopts': {
        '0': '0x0 {}',
        '8': '0x8 {use-failover}',
        '12': '0xC {in-app-browser, use-failover}',
        '24': '0x18 {use-failover, prohibit-encrypted-dns}',
    },
    'mdns:nreason': {
        '1': 'no-data',
        '4': 'query-suppressed',
        '3': 'no-dns-service',
        '2': 'nxdomain',
        '5': 'server error',
    },
    'mdns:protocol': {
        '1': 'UDP',
        '2': 'TCP',
        '4': 'HTTPS',
    },
    'mdns:rrtype': {
        '1': 'A',
        '2': 'NS',
        '5': 'CNAME',
        '6': 'SOA',
        '10': 'NULL',
        '12': 'PTR',
        '13': 'HINFO',
        '15': 'MX',
        '16': 'TXT',
        '17': 'RP',
        '18': 'AFSDB',
        '24': 'SIG',
        '25': 'KEY',
        '28': 'AAAA',
        '29': 'LOC',
        '33': 'SRV',
        '35': 'NAPTR',
        '36': 'KX',
        '37': 'CERT',
        '39': 'DNAME',
        '42': 'APL',
        '43': 'DS',
        '44': 'SSHFP',
        '45': 'IPSECKEY',
        '46': 'RRSIG',
        '47': 'NSEC',
        '48': 'DNSKEY',
        '49': 'DHCID',
        '50': 'NSEC3',
        '51': 'NSEC3PARAM',
        '52': 'TLSA',
        '53': 'SMIMEA',
        '55': 'HIP',
        '59': 'CDS',
        '60': 'CDNSKEY',
        '61': 'OPENPGPKEY',
        '62': 'CSYNC',
        '63': 'ZONEMD',
        '64': 'SVCB',
        '65': 'HTTPS',
        '108': 'EUI48',
        '109': 'EUI64',
        '249': 'TKEY',
        '250': 'TSIG',
        '255': 'ANY',
        '256': 'URI',
        '257': 'CAA',
        '32768': 'TA',
        '32769': 'DLV',
    },
    'odtypes:mbridtype': {
        '0': 'UID',
        '1': 'GID',
        '3': 'SID',
        '4': 'USERNAME',
        '5': 'GROUPNAME',
        '6': 'UUID',
        '7': 'GROUP NFS',
        '8': 'USER NFS',
        '10': 'GSS EXPORT NAME',
        '11': 'X509 DN',
        '12': 'KERBEROS',
    },
    'odtypes:oderror': {
        '5301': 'ODErrorCredentialsAccountDisabled',
        '5302': 'ODErrorCredentialsAccountExpired',
        '5303': 'ODErrorCredentialsAccountInactive',
        '5300': 'ODErrorCredentialsAccountNotFound',
        '5000': 'ODErrorCredentialsInvalid',
        '5001': 'ODErrorCredentialsInvalidComputer',
        '5500': 'ODErrorCredentialsInvalidLogonHours',
        '5100': 'ODErrorCredentialsMethodNotSupported',
        '5101': 'ODErrorCredentialsNotAuthorized',
        '5103': 'ODErrorCredentialsOperationFailed',
        '5102': 'ODErrorCredentialsParameterError',
        '5401': 'ODErrorCredentialsPasswordChangeRequired',
        '5407': 'ODErrorCredentialsPasswordChangeTooSoon',
        '5400': 'ODErrorCredentialsPasswordExpired',
        '5406': 'ODErrorCredentialsPasswordNeedsDigit',
        '5405': 'ODErrorCredentialsPasswordNeedsLetter',
        '5402': 'ODErrorCredentialsPasswordQualityFailed',
        '5403': 'ODErrorCredentialsPasswordTooShort',
        '5404': 'ODErrorCredentialsPasswordTooLong',
        '5408': 'ODErrorCredentialsPasswordUnrecoverable',
        '5205': 'ODErrorCredentialsServerCommunicationError',
        '5202': 'ODErrorCredentialsServerError',
        '5201': 'ODErrorCredentialsServerNotFound',
        '5203': 'ODErrorCredentialsServerTimeout',
        '5200': 'ODErrorCredentialsServerUnreachable',
        '10002': 'ODErrorDaemonError',
        '2100': 'ODErrorNodeConnectionFailed',
        '2002': 'ODErrorNodeDisabled',
        '2200': 'ODErrorNodeUnknownHost',
        '2000': 'ODErrorNodeUnknownName',
        '2001': 'ODErrorNodeUnknownType',
        '10001': 'ODErrorPluginError',
        '10000': 'ODErrorPluginOperationNotSupported',
        '10003': 'ODErrorPluginOperationTimeout',
        '6001': 'ODErrorPolicyOutOfRange',
        '6000': 'ODErrorPolicyUnsupported',
        '3100': 'ODErrorQueryInvalidMatchType',
        '3000': 'ODErrorQuerySynchronize',
        '3102': 'ODErrorQueryTimeout',
        '3101': 'ODErrorQueryUnsupportedMatchType',
        '4102': 'ODErrorRecordAlreadyExists',
        '4201': 'ODErrorRecordAttributeNotFound',
        '4200': 'ODErrorRecordAttributeUnknownType',
        '4203': 'ODErrorRecordAttributeValueNotFound',
        '4202': 'ODErrorRecordAttributeValueSchemaError',
        '4101': 'ODErrorRecordInvalidType',
        '4104': 'ODErrorRecordNoLongerExists',
        '4100': 'ODErrorRecordParameterError',
        '4001': 'ODErrorRecordPermissionError',
        '4000': 'ODErrorRecordReadOnlyNode',
        '4103': 'ODErrorRecordTypeDisabled',
        '1002': 'ODErrorSessionDaemonNotRunning',
        '1003': 'ODErrorSessionDaemonRefused',
        '1000': 'ODErrorSessionLocalOnlyDaemonInUse',
        '1001': 'ODErrorSessionNormalDaemonInUse',
        '1100': 'ODErrorSessionProxyCommunicationError',
        '1102': 'ODErrorSessionProxyIPUnreachable',
        '1103': 'ODErrorSessionProxyUnknownHost',
        '1101': 'ODErrorSessionProxyVersionMismatch',
        '0': 'ODErrorSuccess',
        '5305': 'ODErrorCredentialsAccountLocked',
        '5304': 'ODErrorCredentialsAccountTemporarilyLocked',
        '5204': 'ODErrorCredentialsContactPrimary',
        '2': 'Not Found',
    },
}


def decode(decoder_type: str, raw: str) -> str | None:
    """Return the decoded name for *raw* under *decoder_type*, or None.

    *decoder_type* must be lowercased (callers pass the stripped annotation
    type from message._annotation_type). None means 'no table / no match',
    so the caller can fall back to the raw value.
    """
    table = DECODER_TABLES.get(decoder_type)
    if table is None:
        return None
    return table.get(raw)
